<pre>


</pre>

## Start your mySQL Server from a terminal 
(if it isn't already running)

<code>sudo docker start course-mysql</code>
<pre>

</pre>
Don't forget that, if you use sqlMagic, you need to execute the connection lines in your Notebook!

<pre>
%load_ext sql
%config SqlMagic.autocommit=False
%sql mysql+pymysql://root:root@127.0.0.1:3306/mysql
</pre>

## Create a new Python3 Jupyter Notebook in your Exam Answers folder

Commit and push this Notebook to GitHub when you are finished.

You must submit your answers to GitHub by 1800h Sept 14.

In [2]:
%load_ext sql
%config SqlMagic.autocommit=False
%sql mysql+pymysql://root:root@127.0.0.1:3306/mysql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

'Connected: root@mysql'



## Data Files
Germplasm.tsv and LocusGene.tsv contain the datasets we need for the exam.

Our objective is to create a database to contain the data in these files, insert the data into the database, then query the database in a variety of ways.


## Problem 1:  Controls

Write a Python script that proves that the lines of data in Germplasm.tsv, and LocusGene are in the same sequence, based on the AGI Locus Code (ATxGxxxxxx).  (hint: This will help you decide how to load the data into the database).

### Answer:
We are going to compare if lines of data in Germplasm.tsv and LocusGene.tsv are in the same sequence based on the AGI Locus Code:
* The first character is "A" or "a"
* The second character is "T" or "t"
* The third character is the chromosome number (between 1 and 5)
* The fourth character is "G" or "g"
* The remaining characters are a set of 5 digits (between 0 and 9).

For doing this, we use a Regular Expressions to prove if they have the same sequence and define a function to simplify our job.

In [3]:
import re

def validar_datos (nombre_fichero):
    with open (nombre_fichero) as fichero:
        for linea  in fichero:
            x = linea.split('\t')
            print(x[0])
        
            text = x[0]
            matchObj1 = re.search(r'^[aA][tT][0-5][gG]\d{5}$', text)
            if matchObj1:
                print("Match 'AT*G*****': ", matchObj1.group())
            else:
                print("No Match!")
    fichero.close()

validar_datos("LocusGene.tsv")
validar_datos("Germplasm.tsv")

Locus
No Match!
AT1G01040
Match 'AT*G*****':  AT1G01040
AT1G01060
Match 'AT*G*****':  AT1G01060
AT1G01140
Match 'AT*G*****':  AT1G01140
AT1G01220
Match 'AT*G*****':  AT1G01220
AT2G03720
Match 'AT*G*****':  AT2G03720
AT2G03800
Match 'AT*G*****':  AT2G03800
AT2G04240
Match 'AT*G*****':  AT2G04240
AT2G05210
Match 'AT*G*****':  AT2G05210
AT3G02130
Match 'AT*G*****':  AT3G02130
AT3G02140
Match 'AT*G*****':  AT3G02140
AT3G02230
Match 'AT*G*****':  AT3G02230
AT3G02260
Match 'AT*G*****':  AT3G02260
AT3G02310
Match 'AT*G*****':  AT3G02310
AT3G02680
Match 'AT*G*****':  AT3G02680
AT3G02850
Match 'AT*G*****':  AT3G02850
AT3G02870
Match 'AT*G*****':  AT3G02870
AT3G03260
Match 'AT*G*****':  AT3G03260
AT4G14790
Match 'AT*G*****':  AT4G14790
AT4G15210
Match 'AT*G*****':  AT4G15210
AT4G15560
Match 'AT*G*****':  AT4G15560
AT4G15570
Match 'AT*G*****':  AT4G15570
AT4G15802
Match 'AT*G*****':  AT4G15802
AT4G15880
Match 'AT*G*****':  AT4G15880
AT4G16420
Match 'AT*G*****':  AT4G16420
AT4G16480
Match 'AT*G*****':  AT4G16480
AT5G10480
Match 'AT*G*****':  AT5G10480
AT5G10510
Match 'AT*G*****':  AT5G10510
AT5G11110
Match 'AT*G*****':  AT5G11110
AT5G11260
Match 'AT*G*****':  AT5G11260
AT5G11510
Match 'AT*G*****':  AT5G11510
AT5G12200
Match 'AT*G*****':  AT5G12200
AT5G13290
Match 'AT*G*****':  AT5G13290
Locus
No Match!
AT1G01040
Match 'AT*G*****':  AT1G01040
AT1G01060
Match 'AT*G*****':  AT1G01060
AT1G01140
Match 'AT*G*****':  AT1G01140
AT1G01220
Match 'AT*G*****':  AT1G01220
AT2G03720
Match 'AT*G*****':  AT2G03720
AT2G03800
Match 'AT*G*****':  AT2G03800
AT2G04240
Match 'AT*G*****':  AT2G04240
AT2G05210
Match 'AT*G*****':  AT2G05210
AT3G02130
Match 'AT*G*****':  AT3G02130
AT3G02140
Match 'AT*G*****':  AT3G02140
AT3G02230
Match 'AT*G*****':  AT3G02230
AT3G02260
Match 'AT*G*****':  AT3G02260
AT3G02310
Match 'AT*G*****':  AT3G02310
AT3G02680
Match 'AT*G*****':  AT3G02680
AT3G02850
Match 'AT*G*****':  AT3G02850
AT3G02870
Match 'AT*G*****':  AT3G02870
AT3G03260
Match 'AT*G*****':  AT3G03260
AT4G14790
Match 'AT*G*****':  AT4G14790
AT4G15210
Match 'AT*G*****':  AT4G15210
AT4G15560
Match 'AT*G*****':  AT4G15560
AT4G15570
Match 'AT*G*****':  AT4G15570
AT4G15802
Match 'AT*G*****':  AT4G15802
AT4G15880
Match 'AT*G*****':  AT4G15880
AT4G16420
Match 'AT*G*****':  AT4G16420
AT4G16480
Match 'AT*G*****':  AT4G16480
AT5G10480
Match 'AT*G*****':  AT5G10480
AT5G10510
Match 'AT*G*****':  AT5G10510
AT5G11110
Match 'AT*G*****':  AT5G11110
AT5G11260
Match 'AT*G*****':  AT5G11260
AT5G11510
Match 'AT*G*****':  AT5G11510
AT5G12200
Match 'AT*G*****':  AT5G12200
AT5G13290
Match 'AT*G*****':  AT5G13290

## Problem 2:  Design and create the database.  
* It should have two tables - one for each of the two data files.
* The two tables should be linked in a 1:1 relationship
* you may use either sqlMagic or pymysql to build the database

### Answer:

In [4]:
%sql show databases

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
4 rows affected.

[('information_schema',), ('mysql',), ('performance_schema',), ('sys',)]

In [30]:
%sql CREATE DATABASE germplasm
%sql SHOW databases

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
(pymysql.err.ProgrammingError) (1007, "Can't create database 'germplasm'; database exists")
[SQL: CREATE DATABASE germplasm]
(Background on this error at: http://sqlalche.me/e/f405)
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
5 rows affected.

[('information_schema',),
 ('germplasm',),
 ('mysql',),
 ('performance_schema',),
 ('sys',)]

In [73]:
%sql USE germplasm
%sql CREATE TABLE if not exists germplasm(id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, locus VARCHAR(12) NOT NULL, germplasm VARCHAR(255) NOT NULL, phenotype TEXT NOT NULL, pubmed INT NOT NULL);
%sql DESCRIBE germplasm

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
5 rows affected.

[('id', 'int(11)', 'NO', 'PRI', None, 'auto_increment'),
 ('locus', 'varchar(12)', 'NO', '', None, ''),
 ('germplasm', 'varchar(255)', 'NO', '', None, ''),
 ('phenotype', 'text', 'NO', '', None, ''),
 ('pubmed', 'int(11)', 'NO', '', None, '')]

In [38]:
%sql USE germplasm
#%sql CREATE TABLE if not exists locusgene(id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY, locus VARCHAR(9) NOT NULL, gen VARCHAR(8) NOT NULL, proteinlength INT NOT NULL);
%sql DESCRIBE locusgene

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
4 rows affected.

/home/osboxes/Anaconda/lib/python3.7/site-packages/pymysql/cursors.py:170: Warning: (1050, "Table 'locusgene' already exists")
  result = self._query(query)

[('id', 'int(11)', 'NO', 'PRI', None, 'auto_increment'),
 ('locus', 'varchar(9)', 'NO', '', None, ''),
 ('gen', 'varchar(8)', 'NO', '', None, ''),
 ('proteinlength', 'int(11)', 'NO', '', None, '')]

In [40]:
%sql SELECT germplasm.germplasm, germplasm.phenotype, germplasm.pubmed, locusgene.gen, locusgene.proteinlength, locusgene.locus \
FROM germplasm \
INNER JOIN locusgene ON germplasm.locus=locusgene.locus;
# I think here I can use "locus" as a key because both tables have this column.

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
0 rows affected.

[]

## Problem 3: Fill the database
Using pymysql, create a Python script that reads the data from these files, and fills the database.  There are a variety of strategies to accomplish this.  I will give all strategies equal credit - do whichever one you are most confident with.

### Answer:

In [74]:
def rellenar_datos(nombre_fichero):
    with open (nombre_fichero) as fichero:
        next(fichero)
        for linea  in fichero:
            x = linea.replace("\n", "").split("\t")
            a = x[0]
            b = x[1]
            c = x[2]
            d = int(x[3])
            %sql INSERT INTO germplasm (locus, germplasm, phenotype, pubmed) VALUES (:a, :b, :c, :d);

print(rellenar_datos("Germplasm.tsv"))

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
None

In [79]:
def rellenar_datos2(nombre_fichero):
    with open (nombre_fichero) as fichero:
        next(fichero)
        for linea  in fichero:
            x = linea.split("\t")
            a = x[0]
            b = x[1]
            c = int(x[2])
            %sql INSERT INTO locusgene (locus, gen, proteinlength) VALUES (:a, :b, :c);

print(rellenar_datos2("LocusGene.tsv"))

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
None

## Problem 4: Create reports, written to a file

1. Create a report that shows the full, joined, content of the two database tables (including a header line)

2. Create a joined report that only includes the Genes SKOR and MAA3

3. Create a report that counts the number of entries for each Chromosome (AT1Gxxxxxx to AT5Gxxxxxxx)

4. Create a report that shows the average protein length for the genes on each Chromosome (AT1Gxxxxxx to AT5Gxxxxxxx)

When creating reports 2 and 3, remember the "Don't Repeat Yourself" rule! 

All reports should be written to **the same file**.  You may name the file anything you wish.

In [82]:
# Create a report that shows the full, joined, content of the two database tables (including a header line)
%sql SELECT * FROM germplasm INNER JOIN locusgene ON \
     germplasm.locus = locusgene.locus;

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
32 rows affected.

[(1, 'AT1G01040', 'CS3828', 'Increased abundance of miRNA precursors.', 17369351, 1, 'AT1G01040', 'DCL1', 332),
 (2, 'AT1G01060', 'lhy-101', 'The mutant plants are hypersensitive to both FRc and Rc light treatments in hypocotyl elongation and exhibits a small reciprocal enlargement in cotyledon area, albeit not statistically significant.', 16891401, 2, 'AT1G01060', 'LHY', 290),
 (3, 'AT1G01140', 'SALK_058629', 'hypersensitive to low potassium media', 17486125, 3, 'AT1G01140', 'CIPK9', 223),
 (4, 'AT1G01220', 'SALK_012400C', 'fkgp-1 mutants have about 40 times more L-fucose than wild type Arabidopsis plants, but the levels of other monosaccharides do not appear to differ s ... (41 characters truncated) ... henotypic abnormalities were observed in the fkgp-1 mutants, nor were any differences in the sugar composition of cell wall polysaccharides detected.', 18199744, 4, 'AT1G01220', 'FKGP', 190),
 (5, 'AT2G03720', 'SALK_042433', 'Multiple straight hairs', 16367956, 5, 'AT2G03720', 'MRH6', 189),
 (6, 'AT2G03800', 'gek1-1', 'Ethanol hypersensitivity.', 15215505, 6, 'AT2G03800', 'GEK1', 196),
 (7, 'AT2G04240', 'xerico', 'Resistant to exogenous ABA. Seeds contained lower amounts of endogenous ABA than wildtype.', 17933900, 7, 'AT2G04240', 'XERICO', 256),
 (8, 'AT2G05210', 'pot1-1', 'No visible phenotype.', 17627276, 8, 'AT2G05210', 'POT1A', 221),
 (9, 'AT3G02130', 'rpk2-2', 'The homozygous progeny is indistinguishable from wild-type plants during vegetative growth but showed several morphological alterations after bolting. These plants displayed enhanced inflorescence branching and formed three times as many siliques and flowers as did wild-type plants.', 17419837, 9, 'AT3G02130', 'RPK2', 284),
 (10, 'AT3G02140', 'afp4-1', 'Decreased germination on high concentrations of glucose and sorbitol.', 18484180, 10, 'AT3G02140', 'TMAC2', 300),
 (11, 'AT3G02230', 'rgp1-1', 'rgp1-1 mutants have significantly lower levels of UDP-L-arabinose mutase activity compared to wild-type plants and significantly lower levels of arabinose in their cell walls.', 21478444, 11, 'AT3G02230', 'RGP1', 301),
 (12, 'AT3G02260', 'tir3-1 RGLG1:rglg1 rglg2', 'The triple homozygous progeny has low viability, accumulated anthocyanin, and all plants died before shoot emergence.', 17586653, 12, 'AT3G02260', 'BIG', 279),
 (13, 'AT3G02310', 'sep2-1', 'Non-described subtle phenotype.', 10821278, 13, 'AT3G02310', 'SEP2', 175),
 (14, 'AT3G02680', 'atnbs1-1', 'Significantly smaller when grown in the presence of methyl methanosulfonate (MMS) with root growth.  Normal growth under standard growth conditions.', 17672843, 14, 'AT3G02680', 'NBS1', 190),
 (15, 'AT3G02850', 'CS3816', 'The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion.', 17568770, 15, 'AT3G02850', 'SKOR', 234),
 (16, 'AT3G02870', 'vtc4-1', 'ascorbate deficient', 16595667, 16, 'AT3G02870', 'VTC4', 311),
 (17, 'AT3G03260', 'hdg8-1', 'No visible phenotype.', 16778018, 17, 'AT3G03260', 'HDG8', 194),
 (18, 'AT4G14790', 'pdd17', 'Defective pollen development.', 19237690, 18, 'AT4G14790', 'SUV3', 312),
 (19, 'AT4G15210', 'bmy1-2', 'Plants cold-shocked for 6h have an increased starch content compared to wildtype.', 16297066, 19, 'AT4G15210', 'BAM5', 313),
 (20, 'AT4G15560', 'cla1-1', 'Mutant seeds grown on medium supplemented with non-phosphorylated synthetic 1-deoxy-D-xylulose (DX) develop green leaves.', 10982425, 20, 'AT4G15560', 'DXS', 219),
 (21, 'AT4G15570', 'maa3', 'Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT.', 18772186, 21, 'AT4G15570', 'MAA3', 294),
 (22, 'AT4G15802', 'Athspb-2', 'Early flowering, reduced fertility, aborted seeds.', 20388662, 22, 'AT4G15802', 'HSBP', 254),
 (23, 'AT4G15880', 'esd4-2', 'Decreased mRNA levels of the floral repressors FLC and MAF4 and increased mRNA levels of the floral activators FT and SOC1.', 17513499, 23, 'AT4G15880', 'ESD4', 265),
 (24, 'AT4G16420', 'prz1-1', 'Altered response to auxin and cytokinin', 12747832, 24, 'AT4G16420', 'ADA2B', 279),
 (25, 'AT4G16480', 'atint4-2', 'No visible phenotype.', 16603666, 25, 'AT4G16480', 'INT4', 284),
 (26, 'AT5G10480', 'pas2-3', 'Segregates 25% embryo lethal.', 18799749, 26, 'AT5G10480', 'PAS2', 301),
 (27, 'AT5G10510', 'plt3-1', 'Short roots and shortened root meristem.', 17960244, 27, 'AT5G10510', 'AIL6', 310),
 (28, 'AT5G11110', 'kns2', 'Defects are specific to pollen exine structure. Smaller mesh size in the exine structure. Increased number of baculae. Fully fertile.', 18779216, 28, 'AT5G11110', 'SPS2', 232),
 (29, 'AT5G11260', 'hy5-101', 'Under FRc conditions, the length mutant hypocotyls is increased compared to that of wild-type plants.  Under Rc conditions, the hypocotyl length is also increased and the cotyledon area is smaller.', 16891401, 29, 'AT5G11260', 'HY5', 221),
 (30, 'AT5G11510', 'myb3r4-1', 'No visible phenotype.', 17287251, 30, 'AT5G11510', 'MYB3R-4', 336),
 (31, 'AT5G12200', 'pyd2-2', 'The pyd2-2 mutant has a wild-type appearance under normal growth conditions. Pyrimidine nucleotide and uridine levels are not changed in the mutant, but uracil levels are increased. These mutants cannot grow normally when uracil is provided as a sole nitrogen source.', 19413687, 31, 'AT5G12200', 'PYD2', 310),
 (32, 'AT5G13290', 'crn-1', 'Increased meristem size. Vegetative meristems are are 30% larger than wild type. After bolting inflorescence meristems are enlarged and occasionally fasciated. Flowers occasionally produce extra organs in the first 3.', 12345678, 32, 'AT5G13290', 'CRN', 189)]

In [91]:
# Create a joined report that only includes the Genes SKOR and MAA3
%sql SELECT * FROM germplasm INNER JOIN locusgene ON \
     germplasm.locus = locusgene.locus WHERE locusgene.gen in ("SKOR", "MAA3");

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
2 rows affected.

[(15, 'AT3G02850', 'CS3816', 'The skor-1 mutant is sensitive to toxic cations in addition to K+ depletion.', 17568770, 15, 'AT3G02850', 'SKOR', 234),
 (21, 'AT4G15570', 'maa3', 'Homozygotes are not recovered. Female gametophyte development is delayed and asynchronous. During fertilization, fusion of polar nuclei does not occur. Polar nuclei nucloeli are smaller than WT.', 18772186, 21, 'AT4G15570', 'MAA3', 294)]

In [102]:
#Create a report that counts the number of entries for each Chromosome (AT1Gxxxxxx to AT5Gxxxxxxx)
for i in range(1, 6):
    x = "AT" + str(i) + "%"
    result = %sql select count(*) from germplasm inner join locusgene on germplasm.locus = locusgene.locus where germplasm.locus like :x;
    print("Cromosoma: ", i, result)

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
Cromosoma:  1 +----------+
| count(*) |
+----------+
|    4     |
+----------+
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
Cromosoma:  2 +----------+
| count(*) |
+----------+
|    4     |
+----------+
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
Cromosoma:  3 +----------+
| count(*) |
+----------+
|    9     |
+----------+
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
Cromosoma:  4 +----------+
| count(*) |
+----------+
|    8     |
+----------+

In [101]:
#Create a report that shows the average proteinlength for the genes on each Chromosome (AT1Gxxxxxx to AT5Gxxxxxxx)

%sql SELECT AVG(locusgene.proteinlength) FROM locusgene
# this is the avarage of all chromosome

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.

[(Decimal('258.8750'),)]

In [98]:
for i in range(1, 6):
    x = "AT" + str(i) + "%"
    result = %sql select AVG(locusgene.proteinlength) from germplasm inner join locusgene on germplasm.locus = locusgene.locus where germplasm.locus like :x;
    print("Cromosoma: ", i, result)

 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
Cromosoma:  1 +------------------------------+
| AVG(locusgene.proteinlength) |
+------------------------------+
|           258.7500           |
+------------------------------+
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
Cromosoma:  2 +------------------------------+
| AVG(locusgene.proteinlength) |
+------------------------------+
|           215.5000           |
+------------------------------+
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
Cromosoma:  3 +------------------------------+
| AVG(locusgene.proteinlength) |
+------------------------------+
|           252.0000           |
+------------------------------+
 * mysql+pymysql://root:***@127.0.0.1:3306/mysql
1 rows affected.
Cromosoma:  4 +------------------------------+
| AVG(locusgene.proteinlength) |
+------------------------------+
|           277.5000           |
+------------------------------+

<pre>

</pre>
## Don't forget to commit and push your answers before you leave!

It was wonderful to have you in my class!  I hope to see you again soon!

Good luck with your careers!!

Mark